[package]
name = "file_streaming"
version = "0.0.0"
edition = "2018"
publish = false
workspace = "../../"

[dependencies]
rocket_range = { path = "../../core/lib" }
rocket = "0.4.5"

[dependencies.rocket_contrib]
version = "0.4.5"
default-features = false
features = ["serve"]