[package]
name = "file_streaming"
version = "0.0.0"
edition = "2018"
publish = false
workspace = "../../"

[dependencies]
rocket_range = { path = "../../core/lib" }
rocket = "0.4.5"
rocket_contrib = "0.4.5"